#ifndef SURGE_UI_CONFIG_H
#define SURGE_UI_CONFIG_H

#ifdef SURGE_UI_USER_CONFIG_INCLUDE
#include SURGE_UI_USER_CONFIG_INCLUDE
#endif

#ifndef SURGE_UI_USE_HEADER
#define SURGE_UI_USE_HEADER 1
#endif

#ifndef SURGE_UI_USE_NAV_HEADER
#define SURGE_UI_USE_NAV_HEADER 1
#endif

#ifndef SURGE_UI_USE_FOOTER
#define SURGE_UI_USE_FOOTER 1
#endif

#ifndef SURGE_UI_USE_SECTION_TITLE
#define SURGE_UI_USE_SECTION_TITLE 1
#endif

#ifndef SURGE_UI_USE_EMPTY_STATE
#define SURGE_UI_USE_EMPTY_STATE 1
#endif

#ifndef SURGE_UI_USE_LOADING_STATE
#define SURGE_UI_USE_LOADING_STATE 1
#endif

#ifndef SURGE_UI_USE_TOAST
#define SURGE_UI_USE_TOAST 1
#endif

#ifndef SURGE_UI_USE_PAGE_INDICATOR
#define SURGE_UI_USE_PAGE_INDICATOR 1
#endif

#ifndef SURGE_UI_USE_LIST_VIEW
#define SURGE_UI_USE_LIST_VIEW 1
#endif

#ifndef SURGE_UI_USE_ACTION_BAR
#define SURGE_UI_USE_ACTION_BAR 1
#endif

#ifndef SURGE_UI_USE_SAVE_STATUS_CHIP
#define SURGE_UI_USE_SAVE_STATUS_CHIP 1
#endif

#ifndef SURGE_UI_USE_COMPACT_VALUE_TILE
#define SURGE_UI_USE_COMPACT_VALUE_TILE 1
#endif

#ifndef SURGE_UI_USE_COMPACT_STATUS_TILE
#define SURGE_UI_USE_COMPACT_STATUS_TILE 1
#endif

#ifndef SURGE_UI_USE_SWITCH
#define SURGE_UI_USE_SWITCH 1
#endif

#ifndef SURGE_UI_USE_STEPPER
#define SURGE_UI_USE_STEPPER 1
#endif

#ifndef SURGE_UI_USE_MINI_TREND
#define SURGE_UI_USE_MINI_TREND 1
#endif

#ifndef SURGE_UI_USE_VALUE_TILE
#define SURGE_UI_USE_VALUE_TILE 1
#endif

#ifndef SURGE_UI_USE_VALUE_PAIR
#define SURGE_UI_USE_VALUE_PAIR 1
#endif

#ifndef SURGE_UI_USE_STATUS_ROW
#define SURGE_UI_USE_STATUS_ROW 1
#endif

#ifndef SURGE_UI_USE_STATUS_DOT
#define SURGE_UI_USE_STATUS_DOT 1
#endif

#ifndef SURGE_UI_USE_STATUS_BADGE
#define SURGE_UI_USE_STATUS_BADGE 1
#endif

#ifndef SURGE_UI_USE_ALARM_BANNER
#define SURGE_UI_USE_ALARM_BANNER 1
#endif

#ifndef SURGE_UI_USE_PROGRESS_BAR
#define SURGE_UI_USE_PROGRESS_BAR 1
#endif

#ifndef SURGE_UI_USE_MENU_ROW
#define SURGE_UI_USE_MENU_ROW 1
#endif

#ifndef SURGE_UI_USE_MENU_SELECTED_ROW
#define SURGE_UI_USE_MENU_SELECTED_ROW 1
#endif

#ifndef SURGE_UI_USE_MENU_LIST
#define SURGE_UI_USE_MENU_LIST 1
#endif

#ifndef SURGE_UI_USE_PARAM_ROW
#define SURGE_UI_USE_PARAM_ROW 1
#endif

#ifndef SURGE_UI_USE_PARAM_EDIT_ROW
#define SURGE_UI_USE_PARAM_EDIT_ROW 1
#endif

#ifndef SURGE_UI_USE_RECORD_ROW
#define SURGE_UI_USE_RECORD_ROW 1
#endif

#ifndef SURGE_UI_USE_DETAIL_VALUE
#define SURGE_UI_USE_DETAIL_VALUE 1
#endif

#ifndef SURGE_UI_USE_DETAIL_FIELD_ROW
#define SURGE_UI_USE_DETAIL_FIELD_ROW 1
#endif

#ifndef SURGE_UI_USE_CONFIRM_DIALOG
#define SURGE_UI_USE_CONFIRM_DIALOG 1
#endif

#if SURGE_UI_USE_VALUE_PAIR && !SURGE_UI_USE_VALUE_TILE
#error "SURGE_UI_USE_VALUE_PAIR requires SURGE_UI_USE_VALUE_TILE"
#endif

#if SURGE_UI_USE_MENU_LIST && (!SURGE_UI_USE_MENU_ROW || !SURGE_UI_USE_MENU_SELECTED_ROW)
#error "SURGE_UI_USE_MENU_LIST requires SURGE_UI_USE_MENU_ROW and SURGE_UI_USE_MENU_SELECTED_ROW"
#endif

#if SURGE_UI_USE_PARAM_EDIT_ROW && !SURGE_UI_USE_PARAM_ROW
#error "SURGE_UI_USE_PARAM_EDIT_ROW requires SURGE_UI_USE_PARAM_ROW"
#endif

#endif
