set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(NOT DEFINED ARM_NONE_EABI_PREFIX)
    set(ARM_NONE_EABI_PREFIX arm-none-eabi-)
endif()

set(CMAKE_C_COMPILER ${ARM_NONE_EABI_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${ARM_NONE_EABI_PREFIX}gcc)
set(CMAKE_OBJCOPY ${ARM_NONE_EABI_PREFIX}objcopy CACHE FILEPATH "objcopy")
set(CMAKE_SIZE ${ARM_NONE_EABI_PREFIX}size CACHE FILEPATH "size")

set(CMAKE_EXECUTABLE_SUFFIX_ASM ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C ".elf")

